### PR TITLE
feat: use AssetFragment in queries

### PR DESCRIPTION
**Pull request by leventescheckcyscale**
CYS-3301

### CODE REVIEW

**Review by AndreiStefanie — APPROVED** [review]

**Comment by AndreiStefanie** [comment]
Let's wait with this PR until we deploy graph-assessor to prod

**Comment by mimatache** [comment]
Why are we merging this branch to prod, and not dev to prod?

**Review by mimatache — CHANGES_REQUESTED** [review]
We should be merging dev to main, not the feature branch to main

**Comment by AndreiStefanie** [comment]
> We should be merging dev to main, not the feature branch to main

@mimatache  Not in this case. We wouldn't be able to bring in these changes from dev to main since the two branches have diverged. Until we are done with the Azure controls, this is the simplest approach. We discussed this through

**Pull request closed without merging**
